In [1]:
import numpy as np

In [2]:
a=np.array([1,2,4,5],dtype='int8')

In [3]:
print(a)

[1 2 4 5]


In [4]:
b=np.array([[8,9,6,4],[8,5,3,100]])

In [5]:
print(b)

[[  8   9   6   4]
 [  8   5   3 100]]


In [6]:
# Get dimenshion
a.ndim

1

In [7]:
# Get shape
a.shape

(4,)

In [8]:
# get type
a.dtype

dtype('int8')

In [9]:
# get each item size
a.itemsize

1

In [10]:
# get total size
a.size*a.itemsize
# or
a.nbytes

4

In [11]:
# get total size
a.nbytes

4

# accessing/changing specific elements,rows,colums etc


In [12]:
r=np.array([[1,2,3,4,5,6,7,8,9],[11,12,13,14,15,16,17,18,19]])

In [13]:
print(r)

[[ 1  2  3  4  5  6  7  8  9]
 [11 12 13 14 15 16 17 18 19]]


In [14]:
r[1]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
r[1,-2]

18

In [16]:
r.ndim

2

In [17]:
r[1,-4]

16

In [18]:
# get specific row
r[0,:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# get specific column
r[:,7]

array([ 8, 18])

In [20]:
# getting little more fancy [startindex:endingIndex:stepsize]
r[0,3:8:1]
# here step is 1

array([4, 5, 6, 7, 8])

In [21]:
r[1,5]=20

In [22]:
print(r)

[[ 1  2  3  4  5  6  7  8  9]
 [11 12 13 14 15 20 17 18 19]]


In [23]:
r[:,2]=5
print(r)
r[:,2]=[66,77]
print(r)

[[ 1  2  5  4  5  6  7  8  9]
 [11 12  5 14 15 20 17 18 19]]
[[ 1  2 66  4  5  6  7  8  9]
 [11 12 77 14 15 20 17 18 19]]


3d*example

In [24]:
s=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]])
print(s)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]


In [25]:
# get specific element
s[1,0,2]

9

In [26]:
s[:,1,:]

array([[ 4,  5,  6],
       [11, 12, 13]])

In [27]:
s[:,0,:]

array([[1, 2, 3],
       [7, 8, 9]])

In [28]:
s[:,1,:]=[[9,9,9],[4,4,4]]

In [29]:
print(s)

[[[1 2 3]
  [9 9 9]]

 [[7 8 9]
  [4 4 4]]]


# Initiazing different type of arrays


In [30]:
# initiazing zeroes matrix
d=np.zeros((2,4,4,2))

In [31]:
d

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [32]:
d=np.zeros((2,3))

In [33]:
one=np.ones((3,4,4))
# np.ones(number of boxes,number of rows,number of columns,if added number here it is become 4 dimenshions)

In [34]:
print(one)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [35]:
# any other number than 0 and 1
np.full((2,2),1998,dtype='float32')

array([[1998., 1998.],
       [1998., 1998.]], dtype=float32)

In [36]:
np.full_like(r,67)

array([[67, 67, 67, 67, 67, 67, 67, 67, 67],
       [67, 67, 67, 67, 67, 67, 67, 67, 67]])

In [37]:
# Random decimal number
np.random.rand(4,7,3)

array([[[0.93878868, 0.70100439, 0.22651804],
        [0.54980519, 0.7903179 , 0.4471118 ],
        [0.88224577, 0.93310301, 0.22648766],
        [0.77283179, 0.16389348, 0.291432  ],
        [0.77472933, 0.33101518, 0.15902484],
        [0.99675035, 0.73167219, 0.61239786],
        [0.34847134, 0.8694444 , 0.03553163]],

       [[0.11620815, 0.50887919, 0.3895369 ],
        [0.74597033, 0.6550252 , 0.72704114],
        [0.92365001, 0.64798065, 0.38111343],
        [0.68720919, 0.33510698, 0.00672018],
        [0.53833985, 0.17933936, 0.40869964],
        [0.46253432, 0.16464297, 0.23689744],
        [0.60614345, 0.37727632, 0.21983251]],

       [[0.26829444, 0.74807317, 0.36047321],
        [0.00325642, 0.39255788, 0.23103457],
        [0.42411242, 0.18247503, 0.41176416],
        [0.27375457, 0.64637596, 0.94730459],
        [0.13650985, 0.58965666, 0.18138351],
        [0.11019852, 0.09516826, 0.44361837],
        [0.96674042, 0.03590398, 0.35686934]],

       [[0.74107717, 0.06019

In [38]:
np.random.random_sample(r.shape)

array([[0.63758677, 0.53688113, 0.2220474 , 0.91264784, 0.86088908,
        0.5632178 , 0.10256674, 0.25581133, 0.65408095],
       [0.72338924, 0.17264577, 0.68707318, 0.42018636, 0.76637111,
        0.68702777, 0.98212086, 0.10415449, 0.14316593]])

In [39]:
# random interger values
np.random.randint(7,size=(4,4))

array([[1, 3, 5, 6],
       [6, 2, 4, 4],
       [2, 1, 5, 6],
       [3, 3, 1, 5]])

In [40]:
# identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
arr=np.array([[9,67,45]])
rep=np.repeat(arr,3)
print(rep)

[ 9  9  9 67 67 67 45 45 45]


In [42]:
arr1=np.random.randint(7,size=(3,3))
arr2=np.repeat(arr1,3,axis=1)
print(arr2)

[[2 2 2 5 5 5 2 2 2]
 [5 5 5 0 0 0 5 5 5]
 [4 4 4 1 1 1 3 3 3]]


In [43]:
u=np.ones((5,5))

In [44]:
print(u)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [45]:
p=np.zeros((3,3))
p[1,1]=9 
print(p)


[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [46]:
u[1:4,1:4]=p
print(u)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# be careful when copying array!!!!!


In [48]:
l=np.array([1,2,3,4])
m=l
l[0]=88
print(m)

[88  2  3  4]


In [49]:
print(l)

[88  2  3  4]


In [51]:
# now see this
l=np.array([1,2,3,4])
m=l.copy()
m[0]=88
print(m)


[88  2  3  4]


In [52]:
print(l)

[1 2 3 4]


In [54]:
l+2

array([3, 4, 5, 6])

In [55]:
l-3

array([-2, -1,  1,  2], dtype=int8)

In [56]:
l*3

array([ 3,  6, 12, 15], dtype=int8)

In [58]:
l/2

array([0.5, 1. , 2. , 2.5])

In [59]:
w=np.array([55,66,77,88])
print(l+w)


[56 68 80 92]


In [60]:
print(l-w)

[-54 -64 -74 -84]


In [61]:
print(l*w)

[ 55 132 231 352]


In [62]:
print(l/w)

[0.01818182 0.03030303 0.03896104 0.04545455]


In [63]:
np.sin(l)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [64]:
np.cos(w)

array([ 0.02212676, -0.99964746, -0.03097503,  0.99937328])

# linear algebra


In [66]:
q=np.ones((2,3))

In [67]:
j=np.full((3,2),2)

In [68]:
np.matmul(q,j)

array([[6., 6.],
       [6., 6.]])

In [69]:
x=np.identity(3)
np.linalg.det(x)


1.0

# statistics


In [70]:
stat=np.array([[1,2,3],[4,5,6]])
stat

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
np.min(stat,axis=0)

array([1, 2, 3])

In [73]:
np.min(stat,axis=1)

array([1, 4])

In [76]:
 np.sum(stat,axis=1)

array([ 6, 15])

# reorgnising

In [78]:
before=np.array([[1,2,3],[4,5,6]])
print(before)

[[1 2 3]
 [4 5 6]]


In [79]:
before.shape

(2, 3)

In [85]:
after=before.reshape((3,2))
print(after)

[[1 2]
 [3 4]
 [5 6]]


In [86]:
# verticaly stacking vector
v1=np.array([1,2,3])
v2=np.array([4,5,6])
np.vstack([v1,v2])


array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
# horizontal stacking vector
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6])

# Miscellanous


## load data from file

In [93]:
np.genfromtxt('G:\ML\output_numpy.txt.txt',delimiter='\n')

array([nan, nan, nan, nan])

In [88]:
np.random.randint(7,size=(4,4))

array([[1, 2, 2, 3],
       [2, 0, 2, 1],
       [4, 0, 3, 1],
       [5, 2, 6, 2]])