In [1]:
# import numpy as np
import numpy as np


In [2]:
a=np.array([1,2,3,4,5],dtype='int16')

In [7]:
b=np.array([6,7,8,9],dtype='int8')
# print(a.dtype)

In [19]:
c=np.array([[[1,2,3],[7,6,88],[77,88,34]]])

In [20]:
b.dtype

dtype('int8')

In [21]:
c.ndim

3

In [22]:
c

array([[[ 1,  2,  3],
        [ 7,  6, 88],
        [77, 88, 34]]])

In [7]:
b.itemsize

4

In [8]:
b.item(5)

88

In [9]:
c=np.array([[2,3,4,5,6],[7,8,9,10,11]])

In [10]:
c[0,3]

5

In [11]:
c[1,4]

11

In [12]:
c[:]

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [13]:
c[0:2,1:1]

array([], shape=(2, 0), dtype=int32)

In [14]:
c

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [15]:
c[:,4]

array([ 6, 11])

In [43]:
o=np.zeros(((3,2)))

In [44]:
o.ndim

2

In [45]:
o

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [46]:
o1=np.zeros(((3,2,3)))

In [47]:
o1

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])